version: 0.2
env:
    variables:
        DOTNET_VERSION: '7.0' # The .NET SDK version to use
        BUCKET_NAME: 'none'

phases:
    install:
        runtime-versions:
            dotnet: $DOTNET_VERSION
        commands:
            - echo "Installing .NET Core SDK version $DOTNET_VERSION"
            - dotnet --version
    pre_build:
        commands:
            - echo "Restoring dependencies"
            - dotnet restore
    build:
        commands:
            - echo "Building the project"
            - dotnet build --configuration Release --no-restore
            - echo "Build the AWS SAM application"
            - sam build 
    post_build:
        commmands:
            - echo "Running Client Tests"
            - dotnet test ClientTests\ClientTests.csproj --configuration Release --no-build
            - echo "Running AWS SAM Serverless Tests"
            - dotnet test ServerlessTests\ServerlessTests.csproj --configuration Release --no-build
            - echo "Packaging the application"
            - dotnet lambda package --configuration Release --framework netcoreapp3.1 --output-package bin\Release\netcoreapp3.1\package.zip
            - echo "Uploading the application to S3"
            - aws s3 cp bin\Release\netcoreapp3.1\package.zip s3://$BUCKET_NAME/package.zip
            - echo "Deploying the SAM application"