version: 0.2
env:
    variables:
        DOTNET_VERSION: '8.0' # The .NET SDK version to use
        BUCKET_NAME: 'nedimcodebuild'

phases:
    install:
        runtime-versions:
            dotnet: $DOTNET_VERSION
        commands:
            - echo "Installing .NET Core SDK version $DOTNET_VERSION"
            - dotnet --version
    pre_build:
        commands:
            - echo "Restoring dependencies"
            - dotnet restore
    build:
        commands:
            - echo "Building the project"
            - dotnet build --configuration Release --no-restore
            - echo "Build the AWS SAM application"
            - cd ServerlessAPI
            - sam build
            - cd ..
            - echo "Running Client Tests"
            - dotnet test ClientTests/ClientTests.csproj --configuration Release --no-build
            - echo "Running AWS SAM Serverless Tests"
            - dotnet test ServerlessTests/ServerlessTests.csproj --configuration Release --no-build
    post_build:
        commands:
            - echo "Copy the entire build folder to the S3 bucket"
            - cd ServerlessAPI && aws s3 cp ./.aws-sam/build/* s3://${BUCKET_NAME} --recursive
            - cd .. #need to go back to the root directory

artifacts:
    type: zip
    files:
        - template.yaml

reports:
    Reports:
        files:
            - '**/*'
        base-directory: 'reports'